package Vista;

import Negocio.YogaTranslator;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class JFTraductor extends javax.swing.JFrame {
    YogaTranslator yogatranslator;
    String sanskrito="";
    String ingles="";
    String espaniol="";
    
    private ImageIcon imagen;
    private Icon icono;
    
    public JFTraductor() {
        initComponents();
        this.setLocationRelativeTo(this);
        yogatranslator = new YogaTranslator();
        this.jTAPalabraBaseaEspañol.setEditable(false);
        this.jTAPalabraBaseaIngles.setEditable(false);
        this.jTAIngles.setEditable(false);
        this.jTASanscrito.setEditable(false);
        this.jTASanscritoAEspaniol.setEditable(false);
        this.jTAsanskritoAIngles.setEditable(false);
        this.jTAinglesAEspaniol.setEditable(false);
        this.jTAinglesASanscrito.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTPEspaniol = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTFSanskrit = new javax.swing.JTextField();
        jBSanskrit = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTAsanskritoAIngles = new javax.swing.JTextField();
        jTASanscritoAEspaniol = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTFEspaniol = new javax.swing.JTextField();
        jBEspaniol = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTAIngles = new javax.swing.JTextField();
        jTASanscrito = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jTFIngles = new javax.swing.JTextField();
        jBIngles = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTAinglesAEspaniol = new javax.swing.JTextField();
        jTAinglesASanscrito = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTFpalabraBase = new javax.swing.JTextField();
        jBpalabraBase = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTAPalabraBaseaEspañol = new javax.swing.JTextField();
        jTAPalabraBaseaIngles = new javax.swing.JTextField();
        jLResultado = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Yoga");

        jTPEspaniol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTPEspaniolMouseClicked(evt);
            }
        });

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("Postura:");

        jTFSanskrit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFSanskritKeyPressed(evt);
            }
        });

        jBSanskrit.setText("Buscar");
        jBSanskrit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSanskritActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Inglés");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Español");

        jTAsanskritoAIngles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTAsanskritoAInglesActionPerformed(evt);
            }
        });

        jTASanscritoAEspaniol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTASanscritoAEspaniolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTASanscritoAEspaniol, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTAsanskritoAIngles, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSanskrit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFSanskrit, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(jTFSanskrit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBSanskrit)
                .addGap(34, 34, 34)
                .addComponent(jLabel17)
                .addGap(29, 29, 29)
                .addComponent(jTAsanskritoAIngles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jTASanscritoAEspaniol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        jTPEspaniol.addTab("Sánscrito", jPanel3);

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Postura:");

        jTFEspaniol.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFEspaniolKeyPressed(evt);
            }
        });

        jBEspaniol.setText("Buscar");
        jBEspaniol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEspaniolActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Inglés");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Sánscrito");

        jTAIngles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTAInglesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jBEspaniol, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTFEspaniol, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTASanscrito, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(jTAIngles))
                .addGap(86, 86, 86))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFEspaniol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBEspaniol)
                .addGap(34, 34, 34)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jTAIngles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jTASanscrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        jTPEspaniol.addTab("Español", jPanel5);

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel19.setText("Postura:");

        jBIngles.setText("Buscar");
        jBIngles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInglesActionPerformed(evt);
            }
        });
        jBIngles.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBInglesKeyPressed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Español");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText("Sánscrito");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 33, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jBIngles, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTFIngles, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTAinglesAEspaniol, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addComponent(jTAinglesASanscrito))
                .addGap(73, 73, 73))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jTFIngles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBIngles)
                .addGap(40, 40, 40)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jTAinglesAEspaniol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel21)
                .addGap(26, 26, 26)
                .addComponent(jTAinglesASanscrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );

        jTPEspaniol.addTab("Inglés", jPanel4);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Morfema:");

        jBpalabraBase.setText("Buscar");
        jBpalabraBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBpalabraBaseActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Español:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Inglés:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTAPalabraBaseaIngles, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jBpalabraBase, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTFpalabraBase, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTAPalabraBaseaEspañol))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFpalabraBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBpalabraBase)
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jTAPalabraBaseaEspañol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel9)
                .addGap(29, 29, 29)
                .addComponent(jTAPalabraBaseaIngles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(251, 251, 251))
        );

        jTPEspaniol.addTab("Morfemas", jPanel6);

        jLResultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jTPEspaniol, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTPEspaniol)
                    .addComponent(jLResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTPEspaniolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTPEspaniolMouseClicked
        this.pintarImagen(jLResultado, "");
    }//GEN-LAST:event_jTPEspaniolMouseClicked

    private void jBpalabraBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBpalabraBaseActionPerformed
        String palabraBase = this.jTFpalabraBase.getText().toLowerCase();
        String baseAEspaniol = this.yogatranslator.traducirPalabraBase(palabraBase);
        String baseAIngles = this.yogatranslator.traducirPalabraBaseAIngles(palabraBase);
        this.jTAPalabraBaseaEspañol.setText(baseAEspaniol);
        this.jTAPalabraBaseaIngles.setText(baseAIngles);
        this.estaVacio(palabraBase);
    }//GEN-LAST:event_jBpalabraBaseActionPerformed

    private void jTFSanskritKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFSanskritKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFSanskritKeyPressed

    private void jBSanskritActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSanskritActionPerformed
        String posturaSanskrito = this.jTFSanskrit.getText().toLowerCase();
        espaniol = this.yogatranslator.traducirSanskritoAEspanol(posturaSanskrito);
        ingles = this.yogatranslator.traducirSanskritoAIngles(posturaSanskrito);
        this.jTASanscritoAEspaniol.setText(espaniol);
        this.jTAsanskritoAIngles.setText(ingles);
        this.estaVacio(posturaSanskrito);

        switch(posturaSanskrito){
            case "tadasana" -> this.pintarImagen(this.jLResultado, "src/Recurso/tadasana.jpg");
            case "virabhadrasana i" -> this.pintarImagen(this.jLResultado, "src/Recurso/guerrero1.png");
            case "virabhadrasana ii" -> this.pintarImagen(this.jLResultado, "src/Recurso/guerrero2.jpg");
            case "adho mukha svanasana" -> this.pintarImagen(this.jLResultado, "src/Recurso/adhomukhasvanasana.jpg");
            case "vrikshasana" -> this.pintarImagen(this.jLResultado, "src/Recurso/vrikshasana.jpg");
            case "balasana" -> this.pintarImagen(this.jLResultado, "src/Recurso/balasana.jpg");
            case "ardha bhujangasana" -> this.pintarImagen(this.jLResultado, "src/Recurso/ardhabhujangasana.jpg");
            case "paschimottanasana" -> this.pintarImagen(this.jLResultado, "src/Recurso/paschimottanasana.jpg");
            case "setu bandhasana" -> this.pintarImagen(this.jLResultado, "src/Recurso/setubandhasana.jpg");
            case "shavasana" -> this.pintarImagen(this.jLResultado, "src/Recurso/shavasana.jpg");
            case "trikonasana" -> this.pintarImagen(this.jLResultado, "src/Recurso/trikonasana.jpg");
            case "kumbhakasana" -> this.pintarImagen(this.jLResultado, "src/Recurso/kumbhakasana.jpg");
            case "urdhva mukha svanasana" -> this.pintarImagen(this.jLResultado, "src/Recurso/urdhvamukhasvanasana.jpg");
            case "matsyasana" -> this.pintarImagen(this.jLResultado, "src/Recurso/matsyasana.jpg");
            case "utkatasana" -> this.pintarImagen(this.jLResultado, "src/Recurso/utkatasana.jpg");
            case "malasana" -> this.pintarImagen(this.jLResultado, "src/Recurso/malasana.jpg");
            case "eka pada rajakapotasana" -> this.pintarImagen(this.jLResultado, "src/Recurso/ekapadarajakapotasana.jpg");
            case "urdhva hastasana" -> this.pintarImagen(this.jLResultado, "src/Recurso/urdhvahastasana.jpg");
            case "parivrtta trikonasana" -> this.pintarImagen(this.jLResultado, "src/Recurso/parivrttatrikonasana.jpg");
            case "parivrtta janu sirsasana" -> this.pintarImagen(this.jLResultado, "src/Recurso/parivrtta janu sirsasana.jpg");
            
            default -> {
                    this.jTFSanskrit.setText("");
                    this.pintarImagen(jLResultado, "src/Recurso/incognita.jpg");
                    }
        }
    }//GEN-LAST:event_jBSanskritActionPerformed

    private void jBInglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInglesActionPerformed
        String posturaIngles = this.jTFIngles.getText().toLowerCase();
        sanskrito = this.yogatranslator.traducirInglesASanskrito(posturaIngles);
        espaniol = this.yogatranslator.traducirInglesAEspaniol(posturaIngles);
        this.jTAinglesASanscrito.setText(sanskrito);
        this.jTAinglesAEspaniol.setText(espaniol);
        this.estaVacio(posturaIngles);

        switch(posturaIngles){
            case "mountain pose" -> this.pintarImagen(this.jLResultado, "src/Recurso/tadasana.jpg");
            case "warrior i" -> this.pintarImagen(this.jLResultado, "src/Recurso/guerrero1.png");
            case "warrior ii" -> this.pintarImagen(this.jLResultado, "src/Recurso/guerrero2.jpg");
            case "downward-facing dog" -> this.pintarImagen(this.jLResultado, "src/Recurso/adhomukhasvanasana.jpg");
            case "tree pose" -> this.pintarImagen(this.jLResultado, "src/Recurso/vrikshasana.jpg");
            case "child's pose" -> this.pintarImagen(this.jLResultado, "src/Recurso/balasana.jpg");
            case "half cobra pose" -> this.pintarImagen(this.jLResultado, "src/Recurso/ardhabhujangasana.jpg");
            case "seated forward bend" -> this.pintarImagen(this.jLResultado, "src/Recurso/paschimottanasana.jpg");
            case "bridge pose" -> this.pintarImagen(this.jLResultado, "src/Recurso/setubandhasana.jpg");
            case "corpse pose" -> this.pintarImagen(this.jLResultado, "src/Recurso/shavasana.jpg");
            case "triangle pose" -> this.pintarImagen(this.jLResultado, "src/Recurso/trikonasana.jpg");
            case "plank pose" -> this.pintarImagen(this.jLResultado, "src/Recurso/kumbhakasana.jpg");
            case "upward-facing dog" -> this.pintarImagen(this.jLResultado, "src/Recurso/urdhvamukhasvanasana.jpg");
            case "fish pose" -> this.pintarImagen(this.jLResultado, "src/Recurso/matsyasana.jpg");
            case "chair pose" -> this.pintarImagen(this.jLResultado, "src/Recurso/utkatasana.jpg");
            case "garland pose" -> this.pintarImagen(this.jLResultado, "src/Recurso/malasana.jpg");
            case "pigeon pose" -> this.pintarImagen(this.jLResultado, "src/Recurso/ekapadarajakapotasana.jpg");
            case "upward salute" -> this.pintarImagen(this.jLResultado, "src/Recurso/urdhvahastasana.jpg");
            case "revolved triangle pose" -> this.pintarImagen(this.jLResultado, "src/Recurso/parivrttatrikonasana.jpg");
            case "revolved head to knee pose" -> this.pintarImagen(this.jLResultado, "src/Recurso/parivrtta janu sirsasana.jpg");

            default -> {
                    this.pintarImagen(jLResultado, "src/Recurso/incognita.jpg");
                    this.jTFIngles.setText("");
                    }
        }
    }//GEN-LAST:event_jBInglesActionPerformed

    private void jBInglesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBInglesKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBInglesKeyPressed

    private void jTFEspaniolKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFEspaniolKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFEspaniolKeyPressed

    private void jBEspaniolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEspaniolActionPerformed
        String posturaEspaniol = this.jTFEspaniol.getText().toLowerCase();
        sanskrito = this.yogatranslator.traducirEspaniolASanskrito(posturaEspaniol);
        ingles = this.yogatranslator.traducirEspaniolAIngles(posturaEspaniol);
        this.jTASanscrito.setText(sanskrito);
        this.jTAIngles.setText(ingles);
        this.estaVacio(posturaEspaniol);

        switch(posturaEspaniol){
            case "postura de la montaña" -> this.pintarImagen(this.jLResultado, "src/Recurso/tadasana.jpg");
            case "guerrero i" -> this.pintarImagen(this.jLResultado, "src/Recurso/guerrero1.png");
            case "guerrero ii" -> this.pintarImagen(this.jLResultado, "src/Recurso/guerrero2.jpg");
            case "perro mirando hacia abajo" -> this.pintarImagen(this.jLResultado, "src/Recurso/adhomukhasvanasana.jpg");
            case "postura del arból" -> this.pintarImagen(this.jLResultado, "src/Recurso/vrikshasana.jpg");
            case "postura del niño" -> this.pintarImagen(this.jLResultado, "src/Recurso/balasana.jpg");
            case "postura de la cobra a la mitad" -> this.pintarImagen(this.jLResultado, "src/Recurso/ardhabhujangasana.jpg");
            case "flexión hacia adelante sentado" -> this.pintarImagen(this.jLResultado, "src/Recurso/paschimottanasana.jpg");
            case "postura del puente" -> this.pintarImagen(this.jLResultado, "src/Recurso/setubandhasana.jpg");
            case "postura del cadáver" -> this.pintarImagen(this.jLResultado, "src/Recurso/shavasana.jpg");
            case "postura del triángulo" -> this.pintarImagen(this.jLResultado, "src/Recurso/trikonasana.jpg");
            case "postura de la plancha" -> this.pintarImagen(this.jLResultado, "src/Recurso/kumbhakasana.jpg");
            case "perro mirando hacia arriba" -> this.pintarImagen(this.jLResultado, "src/Recurso/urdhvamukhasvanasana.jpg");
            case "postura del pez" -> this.pintarImagen(this.jLResultado, "src/Recurso/matsyasana.jpg");
            case "postura de la silla" -> this.pintarImagen(this.jLResultado, "src/Recurso/utkatasana.jpg");
            case "postura de la guirnalda" -> this.pintarImagen(this.jLResultado, "src/Recurso/malasana.jpg");
            case "postura de la paloma" -> this.pintarImagen(this.jLResultado, "src/Recurso/ekapadarajakapotasana.jpg");
            case "saludo hacia arriba" -> this.pintarImagen(this.jLResultado, "src/Recurso/urdhvahastasana.jpg");
            case "postura del triángulo invertido" -> this.pintarImagen(this.jLResultado, "src/Recurso/parivrttatrikonasana.jpg");
            case "postura de la cabeza a la rodilla invertida" -> this.pintarImagen(this.jLResultado, "src/Recurso/parivrtta janu sirsasana.jpg");

            default -> {
                    this.pintarImagen(jLResultado, "src/Recurso/incognita.jpg");
                    this.jTFEspaniol.setText("");
                    }
        }
            
    }//GEN-LAST:event_jBEspaniolActionPerformed

    private void jTAInglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTAInglesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTAInglesActionPerformed

    private void jTAsanskritoAInglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTAsanskritoAInglesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTAsanskritoAInglesActionPerformed

    private void jTASanscritoAEspaniolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTASanscritoAEspaniolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTASanscritoAEspaniolActionPerformed
    
    // Método para cargar una imagen desde una ruta y ajustarla al tamaño de un JLabel
    private void pintarImagen(JLabel lb1, String ruta){
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(
                this.imagen.getImage().getScaledInstance(
                        lb1.getWidth(), 
                        lb1.getHeight(), 
                        Image.SCALE_DEFAULT
                )
        ); 
        lb1.setIcon(this.icono);
        this.repaint();
    }
    

    
    // Método para verificar si una cadena está vacía y mostrar un mensaje si es así
    public void estaVacio(String palabra){
        if (palabra.isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese una postura");
        }
    }
    
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFTraductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFTraductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFTraductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFTraductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFTraductor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEspaniol;
    private javax.swing.JButton jBIngles;
    private javax.swing.JButton jBSanskrit;
    private javax.swing.JButton jBpalabraBase;
    private javax.swing.JLabel jLResultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTAIngles;
    private javax.swing.JTextField jTAPalabraBaseaEspañol;
    private javax.swing.JTextField jTAPalabraBaseaIngles;
    private javax.swing.JTextField jTASanscrito;
    private javax.swing.JTextField jTASanscritoAEspaniol;
    private javax.swing.JTextField jTAinglesAEspaniol;
    private javax.swing.JTextField jTAinglesASanscrito;
    private javax.swing.JTextField jTAsanskritoAIngles;
    private javax.swing.JTextField jTFEspaniol;
    private javax.swing.JTextField jTFIngles;
    private javax.swing.JTextField jTFSanskrit;
    private javax.swing.JTextField jTFpalabraBase;
    private javax.swing.JTabbedPane jTPEspaniol;
    // End of variables declaration//GEN-END:variables
}
