package Vista;

import Negocio.YogaTranslator;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class JFTraductor extends javax.swing.JFrame {
    YogaTranslator yogatranslator;
    String sanskrito="";
    String ingles="";
    String espaniol="";
    
    private ImageIcon imagen;
    private Icon icono;
    
    public JFTraductor() {
        initComponents();
        this.setLocationRelativeTo(this);
        yogatranslator = new YogaTranslator();
        this.jTAPalabraBaseaEspañol.setEditable(false);
        this.jTAPalabraBaseaIngles.setEditable(false);
        this.jTAIngles.setEditable(false);
        this.jTASanscrito.setEditable(false);
        this.jTASanscritoAEspaniol.setEditable(false);
        this.jTAsanskritoAIngles.setEditable(false);
        this.jTAinglesAEspaniol.setEditable(false);
        this.jTAinglesASanscrito.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTPEspaniol = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTFIngles = new javax.swing.JTextField();
        jBIngles = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTAinglesAEspaniol = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTAinglesASanscrito = new javax.swing.JTextArea();
        jBNuevoIngles = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTFSanskrit = new javax.swing.JTextField();
        jBSanskrit = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTAsanskritoAIngles = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTASanscritoAEspaniol = new javax.swing.JTextArea();
        jBNuevoSanskrit = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTFEspaniol = new javax.swing.JTextField();
        jBEspaniol = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAIngles = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTASanscrito = new javax.swing.JTextArea();
        jBNuevoEspaniol = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTFpalabraBase = new javax.swing.JTextField();
        jBpalabraBase = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTAPalabraBaseaIngles = new javax.swing.JTextArea();
        jBNuevo = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTAPalabraBaseaEspañol = new javax.swing.JTextArea();
        jLResultado = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Yoga");

        jTPEspaniol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTPEspaniolMouseClicked(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("Postura:");

        jBIngles.setText("Buscar");
        jBIngles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInglesActionPerformed(evt);
            }
        });
        jBIngles.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBInglesKeyPressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Español");

        jTAinglesAEspaniol.setColumns(20);
        jTAinglesAEspaniol.setRows(5);
        jScrollPane7.setViewportView(jTAinglesAEspaniol);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Sánscrito");

        jTAinglesASanscrito.setColumns(20);
        jTAinglesASanscrito.setRows(5);
        jScrollPane8.setViewportView(jTAinglesASanscrito);

        jBNuevoIngles.setText("Nuevo");
        jBNuevoIngles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoInglesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 33, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(jBIngles, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBNuevoIngles, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jTFIngles, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(73, 73, 73))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jTFIngles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBIngles)
                    .addComponent(jBNuevoIngles))
                .addGap(40, 40, 40)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTPEspaniol.addTab("Inglés", jPanel3);

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Postura:");

        jTFSanskrit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFSanskritKeyPressed(evt);
            }
        });

        jBSanskrit.setText("Buscar");
        jBSanskrit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSanskritActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Inglés");

        jTAsanskritoAIngles.setColumns(20);
        jTAsanskritoAIngles.setRows(5);
        jScrollPane5.setViewportView(jTAsanskritoAIngles);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Español");

        jTASanscritoAEspaniol.setColumns(20);
        jTASanscritoAEspaniol.setRows(5);
        jScrollPane6.setViewportView(jTASanscritoAEspaniol);

        jBNuevoSanskrit.setText("Nuevo");
        jBNuevoSanskrit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoSanskritActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                            .addComponent(jBSanskrit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBNuevoSanskrit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jTFSanskrit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(jTFSanskrit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSanskrit)
                    .addComponent(jBNuevoSanskrit))
                .addGap(34, 34, 34)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTPEspaniol.addTab("Sánscrito", jPanel5);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Postura:");

        jTFEspaniol.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFEspaniolKeyPressed(evt);
            }
        });

        jBEspaniol.setText("Buscar");
        jBEspaniol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEspaniolActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Inglés");

        jTAIngles.setColumns(20);
        jTAIngles.setRows(5);
        jScrollPane1.setViewportView(jTAIngles);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Sánscrito");

        jTASanscrito.setColumns(20);
        jTASanscrito.setRows(5);
        jScrollPane2.setViewportView(jTASanscrito);

        jBNuevoEspaniol.setText("Nuevo");
        jBNuevoEspaniol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoEspaniolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jBEspaniol, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBNuevoEspaniol, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jTFEspaniol, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(73, 73, 73))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFEspaniol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBEspaniol)
                    .addComponent(jBNuevoEspaniol))
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTPEspaniol.addTab("Español", jPanel4);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Morfema:");

        jBpalabraBase.setText("Buscar");
        jBpalabraBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBpalabraBaseActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Español:");

        jTAPalabraBaseaIngles.setColumns(20);
        jTAPalabraBaseaIngles.setRows(5);
        jScrollPane3.setViewportView(jTAPalabraBaseaIngles);

        jBNuevo.setText("Nuevo");
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Inglés:");

        jTAPalabraBaseaEspañol.setColumns(20);
        jTAPalabraBaseaEspañol.setRows(5);
        jScrollPane4.setViewportView(jTAPalabraBaseaEspañol);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jBpalabraBase, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTFpalabraBase, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFpalabraBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBpalabraBase)
                    .addComponent(jBNuevo))
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel9)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTPEspaniol.addTab("Traductor", jPanel6);

        jLResultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTPEspaniol, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTPEspaniol, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBpalabraBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBpalabraBaseActionPerformed
        String palabraBase = this.jTFpalabraBase.getText().toLowerCase();
        String baseAEspaniol = this.yogatranslator.traducirPalabraBase(palabraBase);
        String baseAIngles = this.yogatranslator.traducirPalabraBaseAIngles(palabraBase);
        this.jTAPalabraBaseaEspañol.setText(baseAEspaniol);
        this.jTAPalabraBaseaIngles.setText(baseAIngles);
        this.estaVacio(palabraBase);
    }//GEN-LAST:event_jBpalabraBaseActionPerformed

    private void jBEspaniolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEspaniolActionPerformed
        String posturaEspaniol = this.jTFEspaniol.getText().toLowerCase();
        sanskrito = this.yogatranslator.traducirEspaniolASanskrito(posturaEspaniol);
        ingles = this.yogatranslator.traducirEspaniolAIngles(posturaEspaniol);
        this.jTASanscrito.setText(sanskrito);
        this.jTAIngles.setText(ingles);
        this.estaVacio(posturaEspaniol);

        switch(posturaEspaniol){
            case "postura de la montaña" -> this.pintarImagen(this.jLResultado, "src/Recurso/tadasana.jpg");
            case "guerrero i" -> this.pintarImagen(this.jLResultado, "src/Recurso/guerrero1.png");
            case "guerrero ii" -> this.pintarImagen(this.jLResultado, "src/Recurso/guerrero2.jpg");
            case "perro mirando hacia abajo" -> this.pintarImagen(this.jLResultado, "src/Recurso/adhomukhasvanasana.jpg");
            case "postura del arból" -> this.pintarImagen(this.jLResultado, "src/Recurso/vrikshasana.jpg");
            case "postura del niño" -> this.pintarImagen(this.jLResultado, "src/Recurso/balasana.jpg");
            case "postura de la cobra a la mitad" -> this.pintarImagen(this.jLResultado, "src/Recurso/ardhabhujangasana.jpg");
            case "flexión hacia adelante sentado" -> this.pintarImagen(this.jLResultado, "src/Recurso/paschimottanasana.jpg");
            case "postura del puente" -> this.pintarImagen(this.jLResultado, "src/Recurso/setubandhasana.jpg");
            case "postura del cadáver" -> this.pintarImagen(this.jLResultado, "src/Recurso/shavasana.jpg");
            case "postura del triángulo" -> this.pintarImagen(this.jLResultado, "src/Recurso/trikonasana.jpg");
            case "postura de la plancha" -> this.pintarImagen(this.jLResultado, "src/Recurso/kumbhakasana.jpg");
            case "perro mirando hacia arriba" -> this.pintarImagen(this.jLResultado, "src/Recurso/urdhvamukhasvanasana.jpg");
            case "postura del pez" -> this.pintarImagen(this.jLResultado, "src/Recurso/matsyasana.jpg");
            case "postura de la silla" -> this.pintarImagen(this.jLResultado, "src/Recurso/utkatasana.jpg");
            case "postura de la guirnalda" -> this.pintarImagen(this.jLResultado, "src/Recurso/malasana.jpg");
            case "postura de la paloma" -> this.pintarImagen(this.jLResultado, "src/Recurso/ekapadarajakapotasana.jpg");
            case "saludo hacia arriba" -> this.pintarImagen(this.jLResultado, "src/Recurso/urdhvahastasana.jpg");
            case "postura del triángulo invertido" -> this.pintarImagen(this.jLResultado, "src/Recurso/parivrttatrikonasana.jpg");
            case "postura de la cabeza a la rodilla invertida" -> this.pintarImagen(this.jLResultado, "src/Recurso/parivrtta janu sirsasana.jpg");

            default -> this.jTFEspaniol.setText("");
            
        }

    }//GEN-LAST:event_jBEspaniolActionPerformed

    private void jBSanskritActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSanskritActionPerformed
        String posturaSanskrito = this.jTFSanskrit.getText().toLowerCase();
        espaniol = this.yogatranslator.traducirSanskritoAEspanol(posturaSanskrito);
        ingles = this.yogatranslator.traducirSanskritoAIngles(posturaSanskrito);
        this.jTASanscritoAEspaniol.setText(espaniol);
        this.jTAsanskritoAIngles.setText(ingles);
        this.estaVacio(posturaSanskrito);

        switch(posturaSanskrito){
            case "tadasana" -> this.pintarImagen(this.jLResultado, "src/Recurso/tadasana.jpg");
            case "virabhadrasana i" -> this.pintarImagen(this.jLResultado, "src/Recurso/guerrero1.png");
            case "virabhadrasana ii" -> this.pintarImagen(this.jLResultado, "src/Recurso/guerrero2.jpg");
            case "adho mukha svanasana" -> this.pintarImagen(this.jLResultado, "src/Recurso/adhomukhasvanasana.jpg");
            case "vrikshasana" -> this.pintarImagen(this.jLResultado, "src/Recurso/vrikshasana.jpg");
            case "balasana" -> this.pintarImagen(this.jLResultado, "src/Recurso/balasana.jpg");
            case "ardha bhujangasana" -> this.pintarImagen(this.jLResultado, "src/Recurso/ardhabhujangasana.jpg");
            case "paschimottanasana" -> this.pintarImagen(this.jLResultado, "src/Recurso/paschimottanasana.jpg");
            case "setu bandhasana" -> this.pintarImagen(this.jLResultado, "src/Recurso/setubandhasana.jpg");
            case "shavasana" -> this.pintarImagen(this.jLResultado, "src/Recurso/shavasana.jpg");
            case "trikonasana" -> this.pintarImagen(this.jLResultado, "src/Recurso/trikonasana.jpg");
            case "kumbhakasana" -> this.pintarImagen(this.jLResultado, "src/Recurso/kumbhakasana.jpg");
            case "urdhva mukha svanasana" -> this.pintarImagen(this.jLResultado, "src/Recurso/urdhvamukhasvanasana.jpg");
            case "matsyasana" -> this.pintarImagen(this.jLResultado, "src/Recurso/matsyasana.jpg");
            case "utkatasana" -> this.pintarImagen(this.jLResultado, "src/Recurso/utkatasana.jpg");
            case "malasana" -> this.pintarImagen(this.jLResultado, "src/Recurso/malasana.jpg");
            case "eka pada rajakapotasana" -> this.pintarImagen(this.jLResultado, "src/Recurso/ekapadarajakapotasana.jpg");
            case "urdhva hastasana" -> this.pintarImagen(this.jLResultado, "src/Recurso/urdhvahastasana.jpg");
            case "parivrtta trikonasana" -> this.pintarImagen(this.jLResultado, "src/Recurso/parivrttatrikonasana.jpg");
            case "parivrtta janu sirsasana" -> this.pintarImagen(this.jLResultado, "src/Recurso/parivrtta janu sirsasana.jpg");
            
            default -> this.jTFSanskrit.setText("");
                      
        }
        
        

    }//GEN-LAST:event_jBSanskritActionPerformed

    private void jBInglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInglesActionPerformed
        String posturaIngles = this.jTFIngles.getText().toLowerCase();
        sanskrito = this.yogatranslator.traducirInglesASanskrito(posturaIngles);
        espaniol = this.yogatranslator.traducirInglesAEspaniol(posturaIngles);
        this.jTAinglesASanscrito.setText(sanskrito);
        this.jTAinglesAEspaniol.setText(espaniol);
        this.estaVacio(posturaIngles);

        switch(posturaIngles){
            case "mountain pose" -> this.pintarImagen(this.jLResultado, "src/Recurso/tadasana.jpg");
            case "warrior i" -> this.pintarImagen(this.jLResultado, "src/Recurso/guerrero1.png");
            case "warrior ii" -> this.pintarImagen(this.jLResultado, "src/Recurso/guerrero2.jpg");
            case "downward-facing dog" -> this.pintarImagen(this.jLResultado, "src/Recurso/adhomukhasvanasana.jpg");
            case "tree pose" -> this.pintarImagen(this.jLResultado, "src/Recurso/vrikshasana.jpg");
            case "child's pose" -> this.pintarImagen(this.jLResultado, "src/Recurso/balasana.jpg");
            case "half cobra pose" -> this.pintarImagen(this.jLResultado, "src/Recurso/ardhabhujangasana.jpg");
            case "seated forward bend" -> this.pintarImagen(this.jLResultado, "src/Recurso/paschimottanasana.jpg");
            case "bridge pose" -> this.pintarImagen(this.jLResultado, "src/Recurso/setubandhasana.jpg");
            case "corpse pose" -> this.pintarImagen(this.jLResultado, "src/Recurso/shavasana.jpg");
            case "triangle pose" -> this.pintarImagen(this.jLResultado, "src/Recurso/trikonasana.jpg");
            case "plank pose" -> this.pintarImagen(this.jLResultado, "src/Recurso/kumbhakasana.jpg");
            case "upward-facing dog" -> this.pintarImagen(this.jLResultado, "src/Recurso/urdhvamukhasvanasana.jpg");
            case "fish pose" -> this.pintarImagen(this.jLResultado, "src/Recurso/matsyasana.jpg");
            case "chair pose" -> this.pintarImagen(this.jLResultado, "src/Recurso/utkatasana.jpg");
            case "garland pose" -> this.pintarImagen(this.jLResultado, "src/Recurso/malasana.jpg");
            case "pigeon pose" -> this.pintarImagen(this.jLResultado, "src/Recurso/ekapadarajakapotasana.jpg");
            case "upward salute" -> this.pintarImagen(this.jLResultado, "src/Recurso/urdhvahastasana.jpg");
            case "revolved triangle pose" -> this.pintarImagen(this.jLResultado, "src/Recurso/parivrttatrikonasana.jpg");
            case "revolved head to knee pose" -> this.pintarImagen(this.jLResultado, "src/Recurso/parivrtta janu sirsasana.jpg");

            default -> this.jTFIngles.setText("");
        }
    }//GEN-LAST:event_jBInglesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTFSanskritKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFSanskritKeyPressed
        char keyPressed = evt.getKeyChar();
        if(Character.isDigit(keyPressed)){
            JOptionPane.showMessageDialog(null, "Ingrese solo texto");
            this.jTFSanskrit.setText("");
            this.jTFSanskrit.requestFocus();
        }
    }//GEN-LAST:event_jTFSanskritKeyPressed

    private void jBInglesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBInglesKeyPressed
        char keyPressed = evt.getKeyChar();
        if(Character.isDigit(keyPressed)){
            JOptionPane.showMessageDialog(null, "Ingrese solo texto");
            this.jTFIngles.setText("");
            this.jTFIngles.requestFocus();
        }
    }//GEN-LAST:event_jBInglesKeyPressed

    private void jTFEspaniolKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFEspaniolKeyPressed
        char keyPressed = evt.getKeyChar();
        if(Character.isDigit(keyPressed)){
            JOptionPane.showMessageDialog(null, "Ingrese solo texto");
            this.jTFEspaniol.setText("");
            this.jTFEspaniol.requestFocus();
        }
    }//GEN-LAST:event_jTFEspaniolKeyPressed

    private void jTPEspaniolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTPEspaniolMouseClicked
        this.pintarImagen(jLResultado, "");
    }//GEN-LAST:event_jTPEspaniolMouseClicked

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
        this.jTFpalabraBase.setText("");
        this.jTAPalabraBaseaIngles.setText("");
    }//GEN-LAST:event_jBNuevoActionPerformed

    private void jBNuevoEspaniolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoEspaniolActionPerformed
        this.jTFEspaniol.setText("");
        this.jTAIngles.setText("");
        this.jTASanscrito.setText("");
    }//GEN-LAST:event_jBNuevoEspaniolActionPerformed

    private void jBNuevoSanskritActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoSanskritActionPerformed
        this.jTFSanskrit.setText("");
        this.jTASanscritoAEspaniol.setText("");
        this.jTAsanskritoAIngles.setText("");
    }//GEN-LAST:event_jBNuevoSanskritActionPerformed

    private void jBNuevoInglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoInglesActionPerformed
        this.jTFIngles.setText("");
        this.jTAinglesAEspaniol.setText("");
        this.jTAinglesASanscrito.setText("");
    }//GEN-LAST:event_jBNuevoInglesActionPerformed
    
    // Método para cargar una imagen desde una ruta y ajustarla al tamaño de un JLabel
    private void pintarImagen(JLabel lb1, String ruta){
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(
                this.imagen.getImage().getScaledInstance(
                        lb1.getWidth(), 
                        lb1.getHeight(), 
                        Image.SCALE_DEFAULT
                )
        ); 
        lb1.setIcon(this.icono);
        this.repaint();
    }
    
    // Método para verificar si una cadena está vacía y mostrar un mensaje si es así
    public void estaVacio(String palabra){
        if (palabra.isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese una postura");
        }
    }
    
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFTraductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFTraductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFTraductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFTraductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFTraductor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEspaniol;
    private javax.swing.JButton jBIngles;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBNuevoEspaniol;
    private javax.swing.JButton jBNuevoIngles;
    private javax.swing.JButton jBNuevoSanskrit;
    private javax.swing.JButton jBSanskrit;
    private javax.swing.JButton jBpalabraBase;
    private javax.swing.JLabel jLResultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextArea jTAIngles;
    private javax.swing.JTextArea jTAPalabraBaseaEspañol;
    private javax.swing.JTextArea jTAPalabraBaseaIngles;
    private javax.swing.JTextArea jTASanscrito;
    private javax.swing.JTextArea jTASanscritoAEspaniol;
    private javax.swing.JTextArea jTAinglesAEspaniol;
    private javax.swing.JTextArea jTAinglesASanscrito;
    private javax.swing.JTextArea jTAsanskritoAIngles;
    private javax.swing.JTextField jTFEspaniol;
    private javax.swing.JTextField jTFIngles;
    private javax.swing.JTextField jTFSanskrit;
    private javax.swing.JTextField jTFpalabraBase;
    private javax.swing.JTabbedPane jTPEspaniol;
    // End of variables declaration//GEN-END:variables
}
